// Verilated -*- C++ -*-
// DESCRIPTION: Verilator output: Design internal header
// See VMIPS.h for the primary calling header

#ifndef _VMIPS_MIPS_H_
#define _VMIPS_MIPS_H_

#include "verilated.h"
#include "VMIPS__Inlines.h"
class VMIPS__Syms;

//----------

VL_MODULE(VMIPS_MIPS) {
  public:
    // CELLS
    
    // PORTS
    VL_IN8(CLK,0,0);
    VL_IN8(RESET,0,0);
    VL_OUT8(MemRead,0,0);
    VL_OUT8(MemWrite,0,0);
    VL_OUT8(dBlkRead,0,0);
    VL_OUT8(dBlkWrite,0,0);
    VL_OUT8(iBlkRead,0,0);
    VL_OUT8(iBlkWrite,0,0);
    VL_OUT(R2_output,31,0);
    VL_OUT(data_address_2DM,31,0);
    VL_OUT(data_write_2DM,31,0);
    //char	__VpadToAlign20[4];
    VL_OUTW(block_write_2DM,255,0,8);
    VL_OUTW(block_write_2IM,255,0,8);
    VL_IN(PC_init,31,0);
    VL_IN(R2_input,31,0);
    VL_INW(block_read_fDM,255,0,8);
    VL_INW(block_read_fIM,255,0,8);
    
    // LOCAL SIGNALS
    VL_SIG8(no_fetch,0,0);
    VL_SIG8(SYS,0,0);
    VL_SIG8(ALU_control1_IDEXE,5,0);
    VL_SIG8(ALU_control2_IDEXE,5,0);
    VL_SIG8(ALU_control1_EXEM,5,0);
    VL_SIG8(ALU_control2_EXEM,5,0);
    VL_SIG8(wWrRegID_IDREN,4,0);
    VL_SIG8(writeRegister1_IDEXE,4,0);
    VL_SIG8(writeRegister2_IDEXE,4,0);
    VL_SIG8(writeRegister1_EXEM,4,0);
    VL_SIG8(writeRegister2_EXEM,4,0);
    VL_SIG8(writeRegister1_MEMW,4,0);
    VL_SIG8(writeRegister2_MEMW,4,0);
    VL_SIG8(writeRegister1_WBID,4,0);
    VL_SIG8(writeRegister2_WBID,4,0);
    VL_SIG8(writeRegister1_WBEXE,4,0);
    VL_SIG8(writeRegister2_WBEXE,4,0);
    VL_SIG8(Instr1_10_6_IDEXE,4,0);
    VL_SIG8(Instr2_10_6_IDEXE,4,0);
    VL_SIG8(readRegisterA2_IDEXE,4,0);
    VL_SIG8(readRegisterA1_IDEXE,4,0);
    VL_SIG8(readRegisterB1_IDEXE,4,0);
    VL_SIG8(readRegisterB2_IDEXE,4,0);
    VL_SIG8(MemtoReg1_IDEXE,0,0);
    VL_SIG8(MemtoReg2_IDEXE,0,0);
    VL_SIG8(MemtoReg1_EXEM,0,0);
    VL_SIG8(MemtoReg2_EXEM,0,0);
    VL_SIG8(MemtoReg1_MEMW,0,0);
    VL_SIG8(MemtoReg2_MEMW,0,0);
    VL_SIG8(MemRead1_IDEXE,0,0);
    VL_SIG8(MemRead2_IDEXE,0,0);
    VL_SIG8(MemRead1_EXEM,0,0);
    VL_SIG8(MemRead2_EXEM,0,0);
    VL_SIG8(MemWrite1_IDEXE,0,0);
    VL_SIG8(MemWrite2_IDEXE,0,0);
    VL_SIG8(MemWrite1_EXEM,0,0);
    VL_SIG8(MemWrite2_EXEM,0,0);
    VL_SIG8(do_writeback1_WBID,0,0);
    VL_SIG8(do_writeback2_WBID,0,0);
    VL_SIG8(do_writeback1_IDEXE,0,0);
    VL_SIG8(do_writeback2_IDEXE,0,0);
    VL_SIG8(do_writeback1_MEMW,0,0);
    VL_SIG8(do_writeback2_MEMW,0,0);
    VL_SIG8(do_writeback1_EXEM,0,0);
    VL_SIG8(do_writeback2_EXEM,0,0);
    VL_SIG8(do_writeback1_WBEXE,0,0);
    VL_SIG8(do_writeback2_WBEXE,0,0);
    VL_SIG8(taken_branch1_IDIF,0,0);
    VL_SIG8(taken_branch2_IDIF,0,0);
    VL_SIG8(fetchNull1_fID,0,0);
    VL_SIG8(fetchNull2_fID,0,0);
    VL_SIG8(ALUSrc1_IDEXE,0,0);
    VL_SIG8(ALUSrc2_IDEXE,0,0);
    VL_SIG8(ALUSrc1_EXEM,0,0);
    VL_SIG8(ALUSrc2_EXEM,0,0);
    VL_SIG8(FREEZE,0,0);
    VL_SIG8(isRegWrInstr_IDREN,1,0);
    VL_SIG8(MVECT,1,0);
    VL_SIG8(__PVT__DataWriteMode,1,0);
    VL_SIG8(__PVT__IMISS,0,0);
    VL_SIG8(__PVT__DMISS,0,0);
    VL_SIG8(__PVT__branch_misprediction,0,0);
    VL_SIG8(__PVT__wQ_IFID_pushReq,0,0);
    VL_SIG8(__PVT__wQ_IFID_popReq,0,0);
    VL_SIG8(__PVT__wFreezeID,0,0);
    VL_SIG8(__PVT__wQ_IDREN_pushReq,0,0);
    VL_SIG8(__PVT__wtIQ_pushReq,0,0);
    VL_SIG8(__PVT__wtLSQ_pushReq,0,0);
    VL_SIG8(__PVT__wfLSQ_full,0,0);
    VL_SIG8(__PVT__wRF_RW_EXE_ROBPointer,5,0);
    VL_SIG8(__PVT__wRF_RW_EXE_Mem_Instruction,0,0);
    VL_SIG8(__PVT__wRF_RW_EXE_readRegisterB1,5,0);
    VL_SIG8(__PVT__wRF_RW_EXE_Instr1_10_6,4,0);
    VL_SIG8(__PVT__wRF_RW_EXE_ALUSrc1,0,0);
    VL_SIG8(__PVT__wRF_RW_EXE_RegDest,0,0);
    VL_SIG8(__PVT__wRF_RW_EXE_Branch_flag,0,0);
    VL_SIG8(__PVT__wRF_RW_EXE_jump_flag,0,0);
    VL_SIG8(__PVT__wRF_RW_EXE_MemRead1,0,0);
    VL_SIG8(__PVT__wRF_RW_EXE_MemWrite1,0,0);
    VL_SIG8(__PVT__wMEM_RF_write_register_flag,0,0);
    VL_SIG8(__PVT__wRF_RW_EXE_Valid_Instruction,0,0);
    VL_SIG8(__PVT__wEXE_MEM_ROBPointer,5,0);
    VL_SIG8(__PVT__wEXE_MEM_writeRegister1,5,0);
    VL_SIG8(__PVT__wEXE_MEM_ALU_control1,5,0);
    VL_SIG8(__PVT__wEXE_MEM_Mem_Instruction,0,0);
    VL_SIG8(__PVT__wEXE_MEM_RegDest,0,0);
    VL_SIG8(__PVT__wEXE_MEM_Branch_flag,0,0);
    VL_SIG8(__PVT__wEXE_MEM_MemRead1,0,0);
    VL_SIG8(__PVT__wEXE_MEM_MemWrite1,0,0);
    VL_SIG8(__PVT__wEXE_MEM_Hazard,0,0);
    VL_SIG8(__PVT__wEXE_MEM_Valid_Instruction,0,0);
    VL_SIG8(__PVT__wMEM_ROB_writeRegister1,5,0);
    VL_SIG8(__PVT__wMEM_ROB_Branch_flag,0,0);
    VL_SIG8(__PVT__wMEM_ROB_Hazard,0,0);
    VL_SIG8(__PVT__wMEM_EXE_RegDest,0,0);
    VL_SIG8(__PVT__wMEM_ROB_Valid_Instruction,0,0);
    VL_SIG8(__PVT__wCommitFreeze,0,0);
    VL_SIG8(__PVT__wtROB_pushReq,0,0);
    VL_SIG8(__PVT__wtROB_probeIdx,5,0);
    VL_SIG8(__PVT__wfROB_flushALL,0,0);
    VL_SIG8(__PVT__wfRETRAT_copyRetRat,0,0);
    VL_SIG8(__PVT__iCache1__DOT__hit1,0,0);
    VL_SIG8(__PVT__iCache1__DOT__hit2,0,0);
    VL_SIG8(__PVT__iCache1__DOT__waitCount,3,0);
    VL_SIG8(__PVT__dCache1__DOT__hit0,0,0);
    VL_SIG8(__PVT__dCache1__DOT__hit1,0,0);
    VL_SIG8(__PVT__dCache1__DOT__waitCount,3,0);
    VL_SIG8(__PVT__IF1__DOT__wCarryOn,0,0);
    VL_SIG8(__PVT__Q_IFID__DOT__probeIdx_IN,2,0);
    VL_SIG8(__PVT__Q_IFID__DOT__probePushReq_IN,0,0);
    VL_SIG8(__PVT__Q_IFID__DOT__head,2,0);
    VL_SIG8(__PVT__Q_IFID__DOT__tail,2,0);
    VL_SIG8(__PVT__Q_IFID__DOT__count,3,0);
    VL_SIG8(__PVT__Q_IFID__DOT__validPush,0,0);
    VL_SIG8(__PVT__Q_IFID__DOT__validPop,0,0);
    VL_SIG8(__PVT__ID1__DOT__ALU_control1,5,0);
    VL_SIG8(__PVT__ID1__DOT__opcode1,5,0);
    VL_SIG8(__PVT__ID1__DOT__funct1,5,0);
    VL_SIG8(__PVT__ID1__DOT__format1,4,0);
    VL_SIG8(__PVT__ID1__DOT__rt1,4,0);
    VL_SIG8(__PVT__ID1__DOT__writeRegister1,4,0);
    VL_SIG8(__PVT__ID1__DOT__taken_branch1,0,0);
    VL_SIG8(__PVT__ID1__DOT__link1,0,0);
    VL_SIG8(__PVT__ID1__DOT__RegDst1,0,0);
    VL_SIG8(__PVT__ID1__DOT__jump1,0,0);
    VL_SIG8(__PVT__ID1__DOT__branch1,0,0);
    VL_SIG8(__PVT__ID1__DOT__MemRead1,0,0);
    VL_SIG8(__PVT__ID1__DOT__MemtoReg1,0,0);
    VL_SIG8(__PVT__ID1__DOT__MemWrite1,0,0);
    VL_SIG8(__PVT__ID1__DOT__ALUSrc1,0,0);
    VL_SIG8(__PVT__ID1__DOT__RegWrite1,0,0);
    VL_SIG8(__PVT__ID1__DOT__jumpRegister_Flag1,0,0);
    VL_SIG8(__PVT__ID1__DOT__sign_or_zero_Flag1,0,0);
    VL_SIG8(__PVT__ID1__DOT__syscal1,0,0);
    VL_SIG8(__PVT__ID1__DOT__syscalBubbleCounter,1,0);
    VL_SIG8(__PVT__ID1__DOT__comment1,0,0);
    VL_SIG8(__PVT__ID1__DOT__comment3,0,0);
    VL_SIG8(__PVT__Q_IDREN__DOT__probeIdx_IN,2,0);
    VL_SIG8(__PVT__Q_IDREN__DOT__probePushReq_IN,0,0);
    VL_SIG8(__PVT__Q_IDREN__DOT__head,2,0);
    VL_SIG8(__PVT__Q_IDREN__DOT__tail,2,0);
    VL_SIG8(__PVT__Q_IDREN__DOT__count,3,0);
    VL_SIG8(__PVT__Q_IDREN__DOT__validPush,0,0);
    VL_SIG8(__PVT__Q_IDREN__DOT__validPop,0,0);
    VL_SIG8(__PVT__rename__DOT__rIQoverflow,0,0);
    VL_SIG8(__PVT__rename__DOT__rLSQoverflow,0,0);
    VL_SIG8(__PVT__rename__DOT__rPhysDestReg,5,0);
    VL_SIG8(__PVT__rename__DOT__rPhysSrc1Reg,5,0);
    VL_SIG8(__PVT__rename__DOT__rPhysSrc2Reg,5,0);
    VL_SIG8(__PVT__rename__DOT__rFreeLUnderflow,0,0);
    VL_SIG8(__PVT__rename__DOT__wCarryOn,0,0);
    VL_SIG8(__PVT__rename__DOT__wIsMemRead,0,0);
    VL_SIG8(__PVT__rename__DOT__wIsMemWrite,0,0);
    VL_SIG8(__PVT__rename__DOT__wIQpushable,0,0);
    VL_SIG8(__PVT__rename__DOT__wLSQpushable,0,0);
    VL_SIG8(__PVT__rename__DOT__wDestRegReqd,0,0);
    VL_SIG8(__PVT__rename__DOT__wQ_FreeL_pushReq,0,0);
    VL_SIG8(__PVT__rename__DOT__wQ_FreeL_popReq,0,0);
    VL_SIG8(__PVT__rename__DOT__wQ_FreeL_pushData,5,0);
    VL_SIG8(__PVT__rename__DOT__wQ_FreeL_popData,5,0);
    VL_SIG8(__PVT__rename__DOT__freelist__DOT__probeData_IN,5,0);
    VL_SIG8(__PVT__rename__DOT__freelist__DOT__probeIdx_IN,5,0);
    VL_SIG8(__PVT__rename__DOT__freelist__DOT__probePushReq_IN,0,0);
    VL_SIG8(__PVT__rename__DOT__freelist__DOT__head,5,0);
    VL_SIG8(__PVT__rename__DOT__freelist__DOT__tail,5,0);
    VL_SIG8(__PVT__rename__DOT__freelist__DOT__count,6,0);
    VL_SIG8(__PVT__rename__DOT__freelist__DOT__validPush,0,0);
    VL_SIG8(__PVT__rename__DOT__freelist__DOT__validPop,0,0);
    VL_SIG8(__PVT__issue__DOT__wSrc2Rdy,0,0);
    VL_SIG8(__PVT__issue__DOT__wSrc1Rdy,0,0);
    VL_SIG8(__PVT__issue__DOT__rPr,0,0);
    VL_SIG8(__PVT__issue__DOT__wIQselected,0,0);
    VL_SIG8(__PVT__issue__DOT__wLSQselected,0,0);
    VL_SIG8(__PVT__issue__DOT__wIQrdy,0,0);
    VL_SIG8(__PVT__issue__DOT__wLSQrdy,0,0);
    VL_SIG8(__PVT__issue__DOT__PE_Request,3,0);
    VL_SIG8(__PVT__issue__DOT__PE_Grant,3,0);
    VL_SIG8(__PVT__issue__DOT__wLSQ_pushReq,0,0);
    VL_SIG8(__PVT__issue__DOT__wLSQ_popReq,0,0);
    VL_SIG8(__PVT__issue__DOT__LSQ__DOT__probeIdx_IN,3,0);
    VL_SIG8(__PVT__issue__DOT__LSQ__DOT__probePushReq_IN,0,0);
    VL_SIG8(__PVT__issue__DOT__LSQ__DOT__head,3,0);
    VL_SIG8(__PVT__issue__DOT__LSQ__DOT__tail,3,0);
    VL_SIG8(__PVT__issue__DOT__LSQ__DOT__count,4,0);
    VL_SIG8(__PVT__issue__DOT__LSQ__DOT__validPush,0,0);
    VL_SIG8(__PVT__issue__DOT__LSQ__DOT__validPop,0,0);
    VL_SIG8(__PVT__EXE1__DOT__ALU1__DOT__i,4,0);
    VL_SIG8(__PVT__EXE1__DOT__AGU__DOT__i,4,0);
    VL_SIG8(__PVT__MEM1__DOT__ALU_control,5,0);
    VL_SIG8(__PVT__MEM1__DOT__select1_WB,0,0);
    VL_SIG8(__PVT__commit__DOT__wROB_popReq,0,0);
    VL_SIG8(__PVT__commit__DOT__ROB__DOT__head,5,0);
    VL_SIG8(__PVT__commit__DOT__ROB__DOT__tail,5,0);
    VL_SIG8(__PVT__commit__DOT__ROB__DOT__count,6,0);
    VL_SIG8(__PVT__commit__DOT__ROB__DOT__validPush,0,0);
    VL_SIG8(__PVT__commit__DOT__ROB__DOT__validPop,0,0);
    VL_SIG16(__PVT__issue__DOT__request_bus,15,0);
    VL_SIG16(__PVT__issue__DOT__grant_bus,15,0);
    VL_SIG(R2_output_ID,31,0);
    VL_SIG(Instr_fMEM,31,0);
    VL_SIG(Instr_address_2IM,31,0);
    VL_SIG(CIA_IFID,31,0);
    VL_SIG(PCA_IFID,31,0);
    VL_SIG(nextInstruction_address_IDIF,31,0);
    VL_SIG(writeData1_WBID,31,0);
    VL_SIG(writeData2_WBID,31,0);
    VL_SIG(writeData1_WBEXE,31,0);
    VL_SIG(writeData2_WBEXE,31,0);
    VL_SIG(writeData1_MID,31,0);
    VL_SIG(writeData2_MID,31,0);
    VL_SIG(Dest_Value1_IDEXE,31,0);
    VL_SIG(Dest_Value2_IDEXE,31,0);
    VL_SIG(Dest_Value1_EXEM,31,0);
    VL_SIG(Dest_Value2_EXEM,31,0);
    VL_SIG(Instr1_IDREN,31,0);
    VL_SIG(Instr2_IDEXE,31,0);
    VL_SIG(Instr1_EXEM,31,0);
    VL_SIG(Instr2_EXEM,31,0);
    VL_SIG(Instr1_IFID,31,0);
    VL_SIG(Instr2_IFID,31,0);
    VL_SIG(Operand_A1_IDEXE,31,0);
    VL_SIG(Operand_A2_IDEXE,31,0);
    VL_SIG(Operand_B1_IDEXE,31,0);
    VL_SIG(Operand_B2_IDEXE,31,0);
    VL_SIG(aluResult1_EXEM,31,0);
    VL_SIG(aluResult2_EXEM,31,0);
    VL_SIG(aluResult1_EXEID,31,0);
    VL_SIG(aluResult2_EXEID,31,0);
    VL_SIG(aluResult1_MEMW,31,0);
    VL_SIG(aluResult2_MEMW,31,0);
    VL_SIG(aluResult1_WBID,31,0);
    VL_SIG(aluResult2_WBID,31,0);
    VL_SIG(data_read1_MEMW,31,0);
    VL_SIG(data_read2_MEMW,31,0);
    VL_SIG(readDataB1_IDEXE,31,0);
    VL_SIG(readDataB2_IDEXE,31,0);
    VL_SIG(readDataB1_EXEM,31,0);
    VL_SIG(readDataB2_EXEM,31,0);
    VL_SIG(Instr1_fIC,31,0);
    VL_SIG(Instr2_fIC,31,0);
    VL_SIG(__PVT__data_read_fDC,31,0);
    VL_SIG(__PVT__branch_address_COMMIT,31,0);
    //char	__VpadToAlign540[4];
    VL_SIGW(__PVT__wQ_IFID_popData,95,0,3);
    //char	__VpadToAlign556[4];
    VL_SIGW(__PVT__wQ_IDREN_popData,125,0,4);
    VL_SIGW(__PVT__wtIQ_pushData,182,0,6);
    VL_SIGW(__PVT__wtLSQ_pushData,182,0,6);
    VL_SIGW(__PVT__wIQLSQ_popData,136,0,5);
    VL_SIG(__PVT__wRF_RW_EXE_PCA,31,0);
    VL_SIG(__PVT__wRF_RW_EXE_Instr1,31,0);
    VL_SIG(__PVT__wRF_RW_EXE_Operand_A1,31,0);
    VL_SIG(__PVT__wRF_RW_EXE_Operand_B1,31,0);
    VL_SIG(__PVT__wRF_RW_EXE_Dest_Value1,31,0);
    VL_SIG(__PVT__wEXE_MEM_target_PC,31,0);
    VL_SIG(__PVT__wEXE_MEM_aluresult,31,0);
    VL_SIG(__PVT__wEXE_MEM_address,31,0);
    VL_SIG(__PVT__wEXE_MEM_Dest_Value1,31,0);
    VL_SIG(__PVT__wMEM_ROB_target_PC,31,0);
    VL_SIG(__PVT__wMEM_ROB_ALUResult,31,0);
    VL_SIG(__PVT__wMEM_ROB_Dest_Value1,31,0);
    //char	__VpadToAlign692[4];
    VL_SIGW(__PVT__wtROB_pushData,182,0,6);
    VL_SIGW(__PVT__wRetRat,191,0,6);
    VL_SIGW(__PVT__iCache1__DOT__cc0__DOT__valid,1023,0,32);
    VL_SIGW(__PVT__iCache1__DOT__cc0__DOT__dirty,1023,0,32);
    VL_SIGW(__PVT__iCache1__DOT__cc0__DOT__block_out1,255,0,8);
    VL_SIGW(__PVT__iCache1__DOT__cc0__DOT__block_out2,255,0,8);
    VL_SIGW(__PVT__dCache1__DOT__block_out0,255,0,8);
    VL_SIGW(__PVT__dCache1__DOT__block_out1,255,0,8);
    VL_SIGW(__PVT__dCache1__DOT__policy,256,0,9);
    //char	__VpadToAlign1164[4];
    VL_SIGW(__PVT__dCache1__DOT__cc0__DOT__valid,511,0,16);
    VL_SIGW(__PVT__dCache1__DOT__cc0__DOT__dirty,511,0,16);
    VL_SIGW(__PVT__dCache1__DOT__cc1__DOT__valid,511,0,16);
    VL_SIGW(__PVT__dCache1__DOT__cc1__DOT__dirty,511,0,16);
    VL_SIG(__PVT__IF1__DOT__PC,31,0);
    VL_SIG(__PVT__IF1__DOT__FPC,31,0);
    VL_SIGW(__PVT__Q_IFID__DOT__probeData_IN,95,0,3);
    VL_SIG(__PVT__ID1__DOT__com_OpA1,31,0);
    VL_SIG(__PVT__ID1__DOT__com_OpB1,31,0);
    VL_SIG(__PVT__ID1__DOT__signExtended_output1,31,0);
    VL_SIG(__PVT__ID1__DOT__R2_output,31,0);
    VL_SIG(__PVT__ID1__DOT__readDataA1,31,0);
    VL_SIG(__PVT__ID1__DOT__readDataB1,31,0);
    VL_SIG(__PVT__ID1__DOT__Operand_B1,31,0);
    VL_SIG(__PVT__ID1__DOT__wInstr1,31,0);
    VL_SIG(__PVT__ID1__DOT__wPCA,31,0);
    VL_SIGW(__PVT__Q_IDREN__DOT__probeData_IN,125,0,4);
    VL_SIGW(__PVT__rename__DOT__wPushDataIQLSQ,182,0,6);
    VL_SIG(__PVT__rename__DOT__wtarget,31,0);
    //char	__VpadToAlign1524[4];
    VL_SIGW(__PVT__issue__DOT__wRENISS_pushData,182,0,6);
    VL_SIGW(__PVT__issue__DOT__wIQLSQ_pushData,136,0,5);
    //char	__VpadToAlign1572[4];
    VL_SIGW(__PVT__issue__DOT__wLSQ_headData,136,0,5);
    //char	__VpadToAlign1596[4];
    VL_SIGW(__PVT__issue__DOT__wLSQ_tailData,136,0,5);
    //char	__VpadToAlign1620[4];
    VL_SIGW(__PVT__issue__DOT__wIQ_popData,136,0,5);
    //char	__VpadToAlign1644[4];
    VL_SIGW(__PVT__issue__DOT__wLSQ_popData,136,0,5);
    VL_SIG(__PVT__issue__DOT__counter,31,0);
    VL_SIG(__PVT__issue__DOT__pos,31,0);
    VL_SIG(__PVT__issue__DOT__IQcount,31,0);
    VL_SIG(__PVT__issue__DOT__shortIdx,31,0);
    //char	__VpadToAlign1684[4];
    VL_SIGW(__PVT__issue__DOT__LSQ__DOT__probeData_IN,136,0,5);
    VL_SIG(__PVT__EXE1__DOT__aluResult1,31,0);
    VL_SIG(__PVT__EXE1__DOT__address_out,31,0);
    VL_SIG(__PVT__EXE1__DOT__OpA1,31,0);
    VL_SIG(__PVT__EXE1__DOT__Operand1,31,0);
    VL_SIG(__PVT__EXE1__DOT__OpB1,31,0);
    VL_SIG(__PVT__EXE1__DOT__Operand2,31,0);
    VL_SIG(__PVT__EXE1__DOT__OpLS1,31,0);
    VL_SIG(__PVT__EXE1__DOT__OpLS2,31,0);
    VL_SIG(__PVT__EXE1__DOT__HI1,31,0);
    VL_SIG(__PVT__EXE1__DOT__HI2,31,0);
    VL_SIG(__PVT__EXE1__DOT__LO1,31,0);
    VL_SIG(__PVT__EXE1__DOT__LO2,31,0);
    VL_SIG(__PVT__MEM1__DOT__data_read_aligned,31,0);
    VL_SIG(__PVT__MEM1__DOT__aluResult,31,0);
    VL_SIG(__PVT__commit__DOT__retrat_valid,31,0);
    VL_SIGW(__PVT__commit__DOT__wROB_popData,184,0,6);
    VL_SIGW(__PVT__commit__DOT__wROB_probeDataOut,184,0,6);
    VL_SIGW(__PVT__commit__DOT__wROB_probeDataIn,184,0,6);
    VL_SIGW(__PVT__commit__DOT__wROBhead,184,0,6);
    VL_SIG64(__PVT__EXE1__DOT__ALU1__DOT__temp,63,0);
    VL_SIG64(__PVT__EXE1__DOT__AGU__DOT__temp,63,0);
    VL_SIG(Reg_ID[32],31,0);
    VL_SIG(__PVT__iCache1__DOT__cc0__DOT__tags[1024],16,0);
    VL_SIGW(__PVT__iCache1__DOT__cc0__DOT__blocks[1024],255,0,8);
    VL_SIG(__PVT__dCache1__DOT__cc0__DOT__tags[512],17,0);
    VL_SIGW(__PVT__dCache1__DOT__cc0__DOT__blocks[512],255,0,8);
    VL_SIG(__PVT__dCache1__DOT__cc1__DOT__tags[512],17,0);
    VL_SIGW(__PVT__dCache1__DOT__cc1__DOT__blocks[512],255,0,8);
    VL_SIGW(__PVT__Q_IFID__DOT__buffer[8],95,0,3);
    VL_SIGW(__PVT__Q_IDREN__DOT__buffer[8],125,0,4);
    VL_SIG8(__PVT__rename__DOT__renrat[2],5,0);
    //char	__VpadToAlign75962[6];
    VL_SIG8(__PVT__rename__DOT__freelist__DOT__buffer[64],5,0);
    VL_SIG8(__PVT__issue__DOT__busy_bits[64],0,0);
    VL_SIGW(__PVT__issue__DOT__IQ[9],136,0,5);
    //char	__VpadToAlign76276[4];
    VL_SIGW(__PVT__issue__DOT__LSQ__DOT__buffer[16],136,0,5);
    VL_SIG(__PVT__RF_ReadWrite__DOT__Reg[64],31,0);
    VL_SIG8(__PVT__commit__DOT__retrat[32],5,0);
    VL_SIGW(__PVT__commit__DOT__ROB__DOT__buffer[64],184,0,6);
    
    // LOCAL VARIABLES
    VL_SIG8(dCache1__DOT____Vlvbound1,0,0);
    VL_SIG8(issue__DOT____Vcellinp__PE0____pinNumber3,3,0);
    VL_SIG8(issue__DOT____Vcellinp__PE1____pinNumber3,3,0);
    VL_SIG8(issue__DOT____Vcellinp__PE2____pinNumber3,3,0);
    VL_SIG8(issue__DOT____Vcellinp__PE3____pinNumber3,3,0);
    VL_SIG8(issue__DOT____Vlvbound1,0,0);
    VL_SIG8(issue__DOT____Vlvbound2,0,0);
    VL_SIG8(issue__DOT____Vlvbound3,0,0);
    VL_SIG8(__Vdly__iCache1__DOT__waitCount,3,0);
    VL_SIG8(__Vdly__dCache1__DOT__waitCount,3,0);
    VL_SIG8(__Vdly__Q_IFID__DOT__count,3,0);
    VL_SIG8(__Vdly__Q_IFID__DOT__tail,2,0);
    VL_SIG8(__Vdly__Q_IFID__DOT__head,2,0);
    VL_SIG8(__Vdlyvdim0__Q_IFID__DOT__buffer__v0,2,0);
    VL_SIG8(__Vdlyvset__Q_IFID__DOT__buffer__v0,0,0);
    VL_SIG8(__Vdlyvdim0__Q_IFID__DOT__buffer__v1,2,0);
    VL_SIG8(__Vdlyvset__Q_IFID__DOT__buffer__v1,0,0);
    VL_SIG8(__Vdly__Q_IDREN__DOT__count,3,0);
    VL_SIG8(__Vdly__Q_IDREN__DOT__tail,2,0);
    VL_SIG8(__Vdly__Q_IDREN__DOT__head,2,0);
    VL_SIG8(__Vdlyvdim0__Q_IDREN__DOT__buffer__v0,2,0);
    VL_SIG8(__Vdlyvset__Q_IDREN__DOT__buffer__v0,0,0);
    VL_SIG8(__Vdlyvdim0__Q_IDREN__DOT__buffer__v1,2,0);
    VL_SIG8(__Vdlyvset__Q_IDREN__DOT__buffer__v1,0,0);
    VL_SIG8(__Vdly__rename__DOT__rIQoverflow,0,0);
    VL_SIG8(__Vdly__rename__DOT__rLSQoverflow,0,0);
    VL_SIG8(__Vdlyvval__rename__DOT__renrat__v0,5,0);
    VL_SIG8(__Vdlyvset__rename__DOT__renrat__v0,0,0);
    VL_SIG8(__Vdlyvval__rename__DOT__renrat__v1,5,0);
    VL_SIG8(__Vdlyvval__rename__DOT__renrat__v2,5,0);
    VL_SIG8(__Vdlyvval__rename__DOT__renrat__v3,5,0);
    VL_SIG8(__Vdlyvval__rename__DOT__renrat__v4,5,0);
    VL_SIG8(__Vdlyvval__rename__DOT__renrat__v5,5,0);
    VL_SIG8(__Vdlyvval__rename__DOT__renrat__v6,5,0);
    VL_SIG8(__Vdlyvval__rename__DOT__renrat__v7,5,0);
    VL_SIG8(__Vdlyvval__rename__DOT__renrat__v8,5,0);
    VL_SIG8(__Vdlyvval__rename__DOT__renrat__v9,5,0);
    VL_SIG8(__Vdlyvval__rename__DOT__renrat__v10,5,0);
    VL_SIG8(__Vdlyvval__rename__DOT__renrat__v11,5,0);
    VL_SIG8(__Vdlyvval__rename__DOT__renrat__v12,5,0);
    VL_SIG8(__Vdlyvval__rename__DOT__renrat__v13,5,0);
    VL_SIG8(__Vdlyvval__rename__DOT__renrat__v14,5,0);
    VL_SIG8(__Vdlyvval__rename__DOT__renrat__v15,5,0);
    VL_SIG8(__Vdlyvval__rename__DOT__renrat__v16,5,0);
    VL_SIG8(__Vdlyvval__rename__DOT__renrat__v17,5,0);
    VL_SIG8(__Vdlyvval__rename__DOT__renrat__v18,5,0);
    VL_SIG8(__Vdlyvval__rename__DOT__renrat__v19,5,0);
    VL_SIG8(__Vdlyvval__rename__DOT__renrat__v20,5,0);
    VL_SIG8(__Vdlyvval__rename__DOT__renrat__v21,5,0);
    VL_SIG8(__Vdlyvval__rename__DOT__renrat__v22,5,0);
    VL_SIG8(__Vdlyvval__rename__DOT__renrat__v23,5,0);
    VL_SIG8(__Vdlyvval__rename__DOT__renrat__v24,5,0);
    VL_SIG8(__Vdlyvval__rename__DOT__renrat__v25,5,0);
    VL_SIG8(__Vdlyvval__rename__DOT__renrat__v26,5,0);
    VL_SIG8(__Vdlyvval__rename__DOT__renrat__v27,5,0);
    VL_SIG8(__Vdlyvval__rename__DOT__renrat__v28,5,0);
    VL_SIG8(__Vdlyvval__rename__DOT__renrat__v29,5,0);
    VL_SIG8(__Vdlyvval__rename__DOT__renrat__v30,5,0);
    VL_SIG8(__Vdlyvval__rename__DOT__renrat__v31,5,0);
    VL_SIG8(__Vdlyvdim0__rename__DOT__renrat__v32,0,0);
    VL_SIG8(__Vdlyvval__rename__DOT__renrat__v32,5,0);
    VL_SIG8(__Vdlyvset__rename__DOT__renrat__v32,0,0);
    VL_SIG8(__Vdly__rename__DOT__rFreeLUnderflow,0,0);
    VL_SIG8(__Vdly__rename__DOT__freelist__DOT__count,6,0);
    VL_SIG8(__Vdly__rename__DOT__freelist__DOT__tail,5,0);
    VL_SIG8(__Vdly__rename__DOT__freelist__DOT__head,5,0);
    VL_SIG8(__Vdlyvdim0__rename__DOT__freelist__DOT__buffer__v0,5,0);
    VL_SIG8(__Vdlyvval__rename__DOT__freelist__DOT__buffer__v0,5,0);
    VL_SIG8(__Vdlyvset__rename__DOT__freelist__DOT__buffer__v0,0,0);
    VL_SIG8(__Vdlyvdim0__rename__DOT__freelist__DOT__buffer__v1,5,0);
    VL_SIG8(__Vdlyvset__rename__DOT__freelist__DOT__buffer__v1,0,0);
    VL_SIG8(__Vdly__issue__DOT__rPr,0,0);
    VL_SIG8(__Vdly__issue__DOT__LSQ__DOT__count,4,0);
    VL_SIG8(__Vdly__issue__DOT__LSQ__DOT__tail,3,0);
    VL_SIG8(__Vdly__issue__DOT__LSQ__DOT__head,3,0);
    VL_SIG8(__Vdlyvdim0__issue__DOT__LSQ__DOT__buffer__v0,3,0);
    VL_SIG8(__Vdlyvset__issue__DOT__LSQ__DOT__buffer__v0,0,0);
    VL_SIG8(__Vdlyvdim0__issue__DOT__LSQ__DOT__buffer__v1,3,0);
    VL_SIG8(__Vdlyvset__issue__DOT__LSQ__DOT__buffer__v1,0,0);
    VL_SIG8(__Vdlyvdim0__commit__DOT__retrat__v0,4,0);
    VL_SIG8(__Vdlyvval__commit__DOT__retrat__v0,5,0);
    VL_SIG8(__Vdlyvset__commit__DOT__retrat__v0,0,0);
    VL_SIG8(__Vdly__commit__DOT__ROB__DOT__count,6,0);
    VL_SIG8(__Vdly__commit__DOT__ROB__DOT__tail,5,0);
    VL_SIG8(__Vdly__commit__DOT__ROB__DOT__head,5,0);
    VL_SIG8(__Vdlyvdim0__commit__DOT__ROB__DOT__buffer__v0,5,0);
    VL_SIG8(__Vdlyvset__commit__DOT__ROB__DOT__buffer__v0,0,0);
    VL_SIG8(__Vdlyvdim0__commit__DOT__ROB__DOT__buffer__v1,5,0);
    VL_SIG8(__Vdlyvset__commit__DOT__ROB__DOT__buffer__v1,0,0);
    VL_SIG8(__Vdly__ID1__DOT__syscalBubbleCounter,1,0);
    //char	__VpadToAlign78518[2];
    VL_SIGW(issue__DOT____Vlvbound4,136,0,5);
    //char	__VpadToAlign78540[4];
    VL_SIGW(issue__DOT____Vlvbound5,136,0,5);
    //char	__VpadToAlign78564[4];
    VL_SIGW(__Vdlyvval__Q_IFID__DOT__buffer__v0,95,0,3);
    //char	__VpadToAlign78580[4];
    VL_SIGW(__Vdlyvval__Q_IDREN__DOT__buffer__v0,125,0,4);
    VL_SIGW(__Vdlyvval__issue__DOT__LSQ__DOT__buffer__v0,136,0,5);
    //char	__VpadToAlign78620[4];
    VL_SIGW(__Vdlyvval__commit__DOT__ROB__DOT__buffer__v0,184,0,6);
    VL_SIG(__Vdly__Instr2_IFID,31,0);
    VL_SIG(__Vdly__IF1__DOT__FPC,31,0);
    VL_SIG(__Vdly__IF1__DOT__PC,31,0);
    
    // INTERNAL VARIABLES
  private:
    VMIPS__Syms*	__VlSymsp;		// Symbol table
  public:
    
    // PARAMETERS
    
    // CONSTRUCTORS
  private:
    VMIPS_MIPS& operator= (const VMIPS_MIPS&);	///< Copying not allowed
    VMIPS_MIPS(const VMIPS_MIPS&);	///< Copying not allowed
  public:
    VMIPS_MIPS(const char* name="TOP");
    ~VMIPS_MIPS();
    
    // USER METHODS
    
    // API METHODS
    
    // INTERNAL METHODS
    void __Vconfigure(VMIPS__Syms* symsp, bool first);
    static void	_combo__TOP__v__10(VMIPS__Syms* __restrict vlSymsp);
    static void	_combo__TOP__v__16(VMIPS__Syms* __restrict vlSymsp);
    static void	_combo__TOP__v__21(VMIPS__Syms* __restrict vlSymsp);
    static void	_combo__TOP__v__23(VMIPS__Syms* __restrict vlSymsp);
    static void	_combo__TOP__v__6(VMIPS__Syms* __restrict vlSymsp);
    static void	_initial__TOP__v(VMIPS__Syms* __restrict vlSymsp);
    static void	_multiclk__TOP__v__11(VMIPS__Syms* __restrict vlSymsp);
    static void	_multiclk__TOP__v__15(VMIPS__Syms* __restrict vlSymsp);
    static void	_multiclk__TOP__v__20(VMIPS__Syms* __restrict vlSymsp);
    static void	_sequent__TOP__v__12(VMIPS__Syms* __restrict vlSymsp);
    static void	_sequent__TOP__v__13(VMIPS__Syms* __restrict vlSymsp);
    static void	_sequent__TOP__v__17(VMIPS__Syms* __restrict vlSymsp);
    static void	_sequent__TOP__v__18(VMIPS__Syms* __restrict vlSymsp);
    static void	_sequent__TOP__v__2(VMIPS__Syms* __restrict vlSymsp);
    static void	_sequent__TOP__v__3(VMIPS__Syms* __restrict vlSymsp);
    static void	_sequent__TOP__v__4(VMIPS__Syms* __restrict vlSymsp);
    static void	_sequent__TOP__v__7(VMIPS__Syms* __restrict vlSymsp);
    static void	_sequent__TOP__v__8(VMIPS__Syms* __restrict vlSymsp);
    static void	_settle__TOP__v__1(VMIPS__Syms* __restrict vlSymsp);
    static void	_settle__TOP__v__14(VMIPS__Syms* __restrict vlSymsp);
    static void	_settle__TOP__v__19(VMIPS__Syms* __restrict vlSymsp);
    static void	_settle__TOP__v__22(VMIPS__Syms* __restrict vlSymsp);
    static void	_settle__TOP__v__24(VMIPS__Syms* __restrict vlSymsp);
    static void	_settle__TOP__v__5(VMIPS__Syms* __restrict vlSymsp);
    static void	_settle__TOP__v__9(VMIPS__Syms* __restrict vlSymsp);
} VL_ATTR_ALIGNED(64);

#endif  /*guard*/
